# Generated by Django 4.0.3 on 2022-06-08 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealplan',
            old_name='served',
            new_name='date',
        ),
    ]
