# Generated by Django 4.0.3 on 2022-06-09 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_shoppingitem_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingitem',
            unique_together=set(),
        ),
    ]
